spring.application.name=sistemaHospittalarMarcarConsulta

spring.datasource.url=jdbc:postgresql://localhost:5432/sistemaHospitalar
spring.datasource.username=postgres
spring.datasource.password=03032004
spring.jpa.hibernate.ddl-auto=update